// clear input
key_forward = false 
key_right = false 
key_left = false
key_turret_left = false
key_turret_right = false
key_backward = false 
key_change_spawn = false 
key_flag = false 
key_weapon1_pressed = false
key_weapon2_pressed = false 
key_weapon3_pressed = false